#!/bin/bash

run=false

if [ $# == 1 ]; then
    if [ $1 == '-r' || $1 == '-run' ]; then
        run=true
    fi
fi

if [ $run = true ]; then
    stack build --exec haskellcord
else
    stack build
fi
